version: '3.8'

services:
  database:
    image: postgres:15.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: picstagram
