import { Inter } from 'next/font/google';

import { Header } from '@/components/main/Header/Header';
import { Container } from '@/components/ui/Container/Container';
import { PROJECT_NAME } from '@/lib/constants';
import { AppProviders } from '@/providers/AppProviders';

import type { ReactNode } from 'react';

import '@/assets/styles/globals.css';

export const metadata = {
	title: {
		default: PROJECT_NAME,
		template: `%s | ${PROJECT_NAME}`,
	},
	description: 'Generated by create next app',
	themeColor: '#fe67bA',
};

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin', 'latin-ext'],
});

export default function RootLayout({
	children,
}: {
	readonly children: ReactNode;
}) {
	return (
		<html lang="en" className={inter.variable}>
			<body>
				<AppProviders>
					<Header />
					<Container as="main" className="px-2 py-9">
						{children}
					</Container>
				</AppProviders>
			</body>
		</html>
	);
}
